In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('police.csv')

In [3]:
df.head()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91741 entries, 0 to 91740
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           91741 non-null  object
 1   stop_time           91741 non-null  object
 2   county_name         0 non-null      float64
 3   driver_gender       86406 non-null  object
 4   driver_age_raw      86414 non-null  float64
 5   driver_age          86120 non-null  float64
 6   driver_race         86408 non-null  object
 7   violation_raw       86408 non-null  object
 8   violation           86408 non-null  object
 9   search_conducted    91741 non-null  bool
 10  search_type         3196 non-null   object
 11  stop_outcome        86408 non-null  object
 12  is_arrested         86408 non-null  object
 13  stop_duration       86408 non-null  object
 14  drugs_related_stop  91741 non-null  bool
dtypes: bool(2), float64(3), object(10)
memory usage: 9.3+ MB

In [5]:
print(df.isna().sum())

stop_date                 0
stop_time                 0
county_name           91741
driver_gender          5335
driver_age_raw         5327
driver_age             5621
driver_race            5333
violation_raw          5333
violation              5333
search_conducted          0
search_type           88545
stop_outcome           5333
is_arrested            5333
stop_duration          5333
drugs_related_stop        0
dtype: int64

In [6]:
df.columns[(df.isna().sum()==len(df)).values]

Index(['county_name'], dtype='object')

In [7]:
df.dropna(how='all', axis=1,inplace=True)

In [8]:
df[df.duplicated()].head()

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
16,2005-07-19,00:30,M,1982.0,23.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
104,2005-10-03,13:26,M,1975.0,30.0,Black,Speeding,Speeding,False,NaN,Arrest Driver,True,30+ Min,False
117,2005-10-04,00:36,M,1961.0,44.0,White,Special Detail/Directed Patrol,Other,False,NaN,Arrest Driver,True,30+ Min,False
149,2005-10-05,10:00,M,1981.0,24.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
239,2005-10-08,12:30,M,1978.0,27.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
print(df.search_type.nunique())
print(df.search_type.value_counts())

24
Incident to Arrest                                          1214
Probable Cause                                               890
Inventory                                                    220
Reasonable Suspicion                                         197
Protective Frisk                                             160
Incident to Arrest,Inventory                                 129
Incident to Arrest,Probable Cause                            105
Probable Cause,Reasonable Suspicion                           75
Incident to Arrest,Inventory,Probable Cause                   34
Probable Cause,Protective Frisk                               33
Incident to Arrest,Protective Frisk                           32
Inventory,Probable Cause                                      22
Incident to Arrest,Reasonable Suspicion                       13
Inventory,Protective Frisk                                    11
Protective Frisk,Reasonable Suspicion                         11
Incident to Arrest,Inventory,Protective Frisk                 11
Incident to Arrest,Probable Cause,Protective Frisk            10
Incident to Arrest,Probable Cause,Reasonable Suspicion         6
Incident to Arrest,Inventory,Reasonable Suspicion              4
Inventory,Reasonable Suspicion                                 4
Inventory,Probable Cause,Reasonable Suspicion                  2
Inventory,Probable Cause,Protective Frisk                      2
Probable Cause,Protective Frisk,Reasonable Suspicion           1
Incident to Arrest,Protective Frisk,Reasonable Suspicion       1
Name: search_type, dtype: int64

In [11]:
df.search_type.mode()[0]
df.search_type.fillna(df.search_type.mode()[0],inplace=True)

In [12]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 91262 entries, 0 to 91740
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           91262 non-null  object
 1   stop_time           91262 non-null  object
 2   driver_gender       86137 non-null  object
 3   driver_age_raw      86145 non-null  float64
 4   driver_age          85852 non-null  float64
 5   driver_race         86139 non-null  object
 6   violation_raw       86139 non-null  object
 7   violation           86139 non-null  object
 8   search_conducted    91262 non-null  bool
 9   search_type         91262 non-null  object
 10  stop_outcome        86139 non-null  object
 11  is_arrested         86139 non-null  object
 12  stop_duration       86139 non-null  object
 13  drugs_related_stop  91262 non-null  bool
dtypes: bool(2), float64(2), object(10)
memory usage: 9.2+ MB

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False
1,2005-01-18,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False
2,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False
3,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,Incident to Arrest,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False

In [13]:
df.dropna(inplace= True)
df.reset_index(drop=True,inplace=True) 
df

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False
1,2005-01-18,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False
2,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False
3,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,Incident to Arrest,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85840,2015-12-31,20:27,M,1986.0,29.0,White,Speeding,Speeding,False,Incident to Arrest,Warning,False,0-15 Min,False
85841,2015-12-31,20:35,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,Incident to Arrest,Warning,False,0-15 Min,False
85842,2015-12-31,20:45,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,Incident to Arrest,Warning,False,0-15 Min,False
85843,2015-12-31,21:42,M,1993.0,22.0,White,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False
85844,2015-12-31,22:46,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False

In [14]:
df.stop_date = pd.to_datetime(df.stop_date)
df.stop_time = pd.to_datetime(df.stop_time).dt.time
df

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55:00,M,1985.0,20.0,White,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False
1,2005-01-18,08:15:00,M,1965.0,40.0,White,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False
2,2005-01-23,23:15:00,M,1972.0,33.0,White,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False
3,2005-02-20,17:15:00,M,1986.0,19.0,White,Call for Service,Other,False,Incident to Arrest,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00:00,F,1984.0,21.0,White,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85840,2015-12-31,20:27:00,M,1986.0,29.0,White,Speeding,Speeding,False,Incident to Arrest,Warning,False,0-15 Min,False
85841,2015-12-31,20:35:00,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,Incident to Arrest,Warning,False,0-15 Min,False
85842,2015-12-31,20:45:00,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,Incident to Arrest,Warning,False,0-15 Min,False
85843,2015-12-31,21:42:00,M,1993.0,22.0,White,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False
85844,2015-12-31,22:46:00,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,Incident to Arrest,Citation,False,0-15 Min,False